### ISSUE TITLE
Always_comb Blocks Lesson

### ISSUE THREAD

**Issue by NyloxtheBard** [byuccl/digital_design_colab#100]
[Reference](https://colab.research.google.com/github/byuccl/digital_design_colab2/blob/master/Exercises/always_comb/always_comb.ipynb#scrollTo=bTcrWL-Gsocg)

-Seems more of an introduction/tutorial than a lesson, information is good, there just isn't much information here or any practice till later.
-Format at the end is wonky, empty line and font of "always comb allows multiple lines" is big, doesn't make much sense if there is supposed to be information here or not.
-I would either combine this lesson with another one that contains more practice or flesh this one out more, or change it to a tutorial type

**Comment by jamilkhalaf** [comment]
- The lesson is kind of clear and straightforward. 
- I would suggest to emphasize that always_comb blocks are specifically used for combinational logic. You might briefly mention other types of always blocks, such as always_ff for sequential logic.
- You mention latches but provide a limited explanation. It might be beneficial to include a brief description of what a latch is in the context of digital design and why it can be problematic.

**Comment by NyloxtheBard** [comment]
Going through this again, I think that this lesson is good to stand on its own, as it does cover quite a bit of stuff and stands on its own fine. I fixed the formatting issue quickly, along with added how always_comb blocks are used specifically for combinational logic. I disagree with needing to add more about latches, but I did add where more information could be found.

**Comment by NyloxtheBard** [comment]
Updated and finished
