### ISSUE TITLE
Flip Flop Lessons

### ISSUE THREAD

**Issue by NyloxtheBard** [byuccl/digital_design_colab#101]
[Reference](https://colab.research.google.com/github/byuccl/digital_design_colab2/blob/master/Exercises/flip_flops/flip_flops.ipynb)

-Typo in first paragraph, second sentence, "immediately"
- The first and third image in the SR Latch section do not appear for me
- The truth table is broken, as Jamil mentioned. It is inconsistent with its errors, and only once was I able to get it to work properly without showing me the answers beforehand. If you go to Runtime up top and run all, the table won't appear at all, and if you just run the setup it seems to just show the answers. The header of the truth table also only reads "none" instead of what the table actually is. It seems to run fine  in VS code, except for the header, so it may be an issue with the compiler for Google Colab.
- The second image in the SR Latch section doesn't make sense, and a walk through as to what is happening with each of the sections would be nice. 
![Screenshot from 2023-12-07 18-11-27](https://github.com/byuccl/digital_design_colab/assets/143136042/4272edb6-3ca1-4371-8aca-eed26db3cf81)

**Comment by jamilkhalaf** [comment]
- There are two images which are not showing in the SR latch section at the beginning of the lesson.
- The truth table provided working has a bug in it, sometimes it would be run before I actually run it, and sometimes it is not running at all. This is how it looks. 
<img width="1710" alt="Screenshot 2023-12-07 at 6 05 25 PM" src="https://github.com/byuccl/digital_design_colab/assets/144198709/d241aa6a-9bfc-4587-ae51-faeafecc1cf4">
- The diagrams of the flip flops are well explained but lacks examples. providing an example such as a truth table for each flip flop will make us understand it better. 
- The explanation of the master-slave latch design is concise but could benefit from a bit more detail. For example, elaborating on why the clock signal is inverted before reaching the slave and how this helps in preventing conflicts or race conditions would enhance understanding.

**Comment by NyloxtheBard** [comment]
After going through this lesson again, it makes a lot more sense. The issues that are still present could be fixed by simply adding more information and descriptions of what is happening.

**Comment by NyloxtheBard** [comment]
Updated and finished
