### ISSUE TITLE
Arithmetic Lab

### ISSUE THREAD

**Issue by NyloxtheBard** [byuccl/digital_design_colab#107]
[Reference](https://colab.research.google.com/github/byuccl/digital_design_colab/blob/master/Labs/arithmetic_lab/arithmetic_lab.ipynb#scrollTo=jkKm3WaizMYC)

When running the Compiling the F4PGA Toolchain, would be good to have an indicator how long each step should take, so that it can be restarted if taking too long to compile conda environment or something else fails. 
![Screenshot from 2023-12-15 18-12-49](https://github.com/byuccl/digital_design_colab/assets/143136042/1f61856f-035a-4a2d-b2a2-0b177b8bf656)

**Comment by jamilkhalaf** [comment]
The arithmetic lab is kind of clear but it does not explain everything. It is pretty good in explaining how each module works with the examples and answers provided, but some sections does not have enough examples such as the section where it explains how subtraction works and how to check for overflow using two's complement. So maybe adding an example would make it clearer.

**Comment by NyloxtheBard** [comment]
added run times, issue fixed with commit
