### ISSUE TITLE
seven segment lab

### ISSUE THREAD

**Issue by jamilkhalaf** [byuccl/digital_design_colab#109]
[reference](https://colab.research.google.com/github/byuccl/digital_design_colab/blob/master/Labs/seven_segment_lab/seven_segment_lab.ipynb)

There is a mistake in the seven segment lab in the first example provided where it converts binary to hex. In the example provided it says 1100 binary is A, but it is supposed to be C.

**Comment by NyloxtheBard** [comment]
Issue is resolved
