### ISSUE TITLE
Refactor widget code so that it uses a standard template 

### ISSUE THREAD

**Issue by westonMS** [byuccl/digital_design_colab#13]
Refactor widget code so that each instance, (e.g. truthtables_algebra.py") uses the templates functions and just has unique dictionaries .

-Have all widgets use the template
-Have exercise use their own file that only contains the files
-Rewrite the import to also come from one base file. (Jinja?) create a new function for grabbing from the Template folder

**Comment by Zach227** [comment]
Don't forget to change how the set up works with these files.
