### ISSUE TITLE
Notebook functionality widget open and unreponsive on page load

### ISSUE THREAD

**Issue by resoluteprogrammer** [byuccl/digital_design_colab#16]
When notebook_functionality.ipynb is first opened it shows that the truth table example has already ran at an unknown time. The widget is displayed but unresponsive. Running the widget code causes the widget to become responsive.

I'm unsure if this behavior is intended but it is not consistent with other pages.

**Comment by westonMS** [comment]
This behavior is consistent with Google Colabs. It can save the output of a Notebook which includes the widgets appearance. This output is loaded when the notebook is loaded but the scripts behind the widget are not.
