### ISSUE TITLE
Create a notebook to demonstrate how to use VSCode with Google drive

### ISSUE THREAD

**Issue by wirthlin** [byuccl/digital_design_colab#34]
The editors are difficult to use for HDL code. Explore the ability to edit files in Google Drive with VS code. Provide some examples.

https://marketplace.visualstudio.com/items?itemName=GustavoASC.google-drive-vscode

**Comment by Vandensj** [comment]
There is a third-party extension for using google drive for VSCode. It allows you to access all files on your google drive, download them, and upload files to your drive. It requires a google cloud platform account which will need to be payed for, here is a link to the setup instructions https://github.com/GustavoASC/google-drive-vscode/blob/HEAD/setup-guide/setup-guide.md
Probably not practical for high school students.
