### ISSUE TITLE
Increase the size of the textboxes

### ISSUE THREAD

**Issue by wirthlin** [byuccl/digital_design_colab#35]
The textboxes for the HDL code are small. Make them much wider and if possible increase the font size. This is closely related to #2

**Comment by adamshaeffer** [comment]
Changing the actual sizes of the textboxes is simple enough: 

- Inside `simulation.py` (one of the files in most labs), around line 670 there should be a method `createSimulationWorkSpace`
- In the definition of the parameters, the four values: `ht`, `wid`, `stht`, and `stwid` define the height and width of the source code and simulation code.
    - Simulation code box height and width are prefixed by 'st'
- The official layout should have the following:
```
def createSimulationWorkSpace(
    initialContents=None, ht="500px", wid="750px", stht="300px", stwid="750px"
):
```

I will be changing the appropriate files and submitting a pull request soon.

**Comment by adamshaeffer** [comment]
#39 Fixes all of them. Though the last lab, state-machines, still might need it. I'm not sure if it's supposed to have a simulation or not.

**Comment by adamshaeffer** [comment]
New requests to reorganize the simulation workspace.

**Comment by adamshaeffer** [comment]
Reorganized the simulation workspaces in the labs (and lab tutorial) to be more easily understood and to look nicer. In all of them: further increased size of simulation code space, changed the order and layout of the buttons to the side of input source code, and added borders to the buttons to look more streamlined.
