### ISSUE TITLE
Twos Complement

### ISSUE THREAD

**Issue by NyloxtheBard** [byuccl/digital_design_colab#95]
[Reference](https://colab.research.google.com/github/byuccl/digital_design_colab/blob/master/Exercises/twos_compliment/twos_compliment.ipynb#scrollTo=yrvMTti3-CK4)

- First, while I think this lab does a great job introducing two compliments in concern to binary system, I just think there needs to be more basic practice with binary beforehand, either moving this lesson further back with the binary [lesson](https://colab.research.google.com/github/byuccl/digital_design_colab/blob/master/Exercises/binary_hex/binary_hex.ipynb) along with maybe including a refresher as to how to calculate binary if moving it is inconvenient. 
- The examples given of the 2 complement I found to be confusing, and I had to do further research on it. I believe an example of a 5 bit starting with a 1 and starting with a zero and walking through the steps for each of them would add further clarity to the lesson, and the same thing with the inverse. Just a clear step by step would improve this lesson greatly. 
- There needs to be instructions as to how to increase a 4 bit to 8 bit aka the concept in general, as the exercise doesn't seem to go over it very well, because I missed it if it is there. 
- Overall, what is being taught is good, just the bare minimum of true understanding and practice, and just needs to be fleshed out more

**Comment by jamilkhalaf** [comment]
I found this lab kind of easy and straightforward. Th explanation at the beginning is good and clear, and the exercises and also great for understanding. I already knew the difference between sign-magnitude number and number, so explaining this before the exercises would be helpful. Explaining that sign-magnitude means that treating the left-most digit just as a sign without considering its value while converting to decimal.

**Comment by NyloxtheBard** [comment]
Going through this again, I think this lesson is easy and straightforward. The major issues have been addressed by sorting the lessons and moving the placement of this lesson, so I don't think more needs to be added to it currently.
