### ISSUE TITLE
Addition and Subtraction Lesson

### ISSUE THREAD

**Issue by NyloxtheBard** [byuccl/digital_design_colab#96]
[Reference](https://colab.research.google.com/github/byuccl/digital_design_colab/blob/master/Exercises/addition_subtraction/addition_subtraction.ipynb#scrollTo=OEklN5fX-CQ1)
- The lesson is fine, just should have been covered sooner in the basics, the order for the teachings of binary is very wonky which makes it hard to learn
- A case where there is a 1 carried over to a column with 1 1 would be a good example to cover, as it isn't detailed very clearly, as shown by the second question
- The questions are good, just need better explanations and going through more than just one case and problem. Most people don't see the pattern on the first case, needs more exposure before giving problems. Example questions where there is hand holding would be good, for each of the different groups of questions

**Comment by jamilkhalaf** [comment]
The addition and subtraction lesson is kind short and clear for me because I already knew that. Maybe going through some examples of how to deal with the carry before doing the exercises would be helpful.

**Comment by NyloxtheBard** [comment]
Looking through this lesson again, it seems pretty clear and covers what it needs to. I don't think any improvements need to be made
