### ISSUE TITLE
luts and mux

### ISSUE THREAD

**Issue by jamilkhalaf** [byuccl/digital_design_colab#98]
[reference](https://colab.research.google.com/github/byuccl/digital_design_colab/blob/master/Exercises/luts_and_mux/luts_and_mux.ipynb)

This lesson is clear but could have been done better if it provided an example about mux and go a step by step through its truth table to make sure we understand it. 

The questions are good but I suggest to add a question or two one at the end to help us understand the idea of how a mux work better. The questions can be truth tables and ask us what the output is gonna be for different input signals.

**Comment by NyloxtheBard** [comment]
-What is sel? Elaborate how it is the control signal in introduction of what is a MUX
-Typo in example when talking about how to get output c, needs to be s1 and s2 to match image
-Lesson is very detailed, however will need to be revisited to see if the practice questions allow for more grasp of concept.

**Comment by NyloxtheBard** [comment]
I addressed the issues and added a few things, otherwise the issues we had are now addressed
